

manager.renderer._type: wd-renderer


highlight-size: 2.1
highlight-width: 0.3

sc-size: 1.7
capital-size: 1.9
home-size: 0.4
sc-edge-width: 0.05
home-edge-width: 0.02

unit-size: 1.5
unit-edge-width: 0.35

arrow-ratio: 0.9
arrow-width: 3
arrow-head: 8
edge-width: 0.2


hold-color: <>sup-color
sup-color: y
convoy-color: c
edge-color: k

wedge-dot-size: 0.7

support-style: wedge,tail_width=0.05,shrink_factor=0.5
support-shrink: 0

support-defend-style: wedge,tail_width=0.075,shrink_factor=0.5
support-defend-shrink: 0.2

convoy-style: wedge,tail_width=0.05,shrink_factor=0.5
convoy-shrink: 0

sc-props:
  markersize: <>sc-size
  markeredgewidth: <>sc-edge-width

  markeredgecolor: k
  markerfacecolor: '#FFD700'
  marker: [5,1]
  ls: ''
  zorder: 60
capital-props:
  markersize: <>capital-size
  markeredgewidth: <>sc-edge-width
  markeredgecolor: k
  markerfacecolor: '#FFD700'
  marker: [7, 1]
  ls: ''
  zorder: 60
home-props:
  markeredgewidth: <>home-edge-width
  markeredgecolor: k
  markersize: <>home-size
  marker: o
  ls: ''
  zorder: 61
core-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: '#964b00'
  mfc: None
  zorder: 50
  ls: ''
  shape: D # d


unit-props:
  ms: <>unit-size
  mew: <>unit-edge-width
  zorder: 20
  mec: k
  ls: ''

retreat-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  fc: r
  ec: k
  zorder: 19
retreat-action-arrow: <>retreat-arrow
retreat-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: o
disband-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: x

hold-props:
  color: <>hold-color
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
  mfc: 'none'
  zorder: 21
build-props:
  color: '#00ff00'
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
#  mfc: 'none'
  zorder: 6

move-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: w
  edgecolor: k
  zorder: 15

support-arrow:
  width: <>arrow-width
  ls: --
  fc: <>sup-color
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: <>sup-color
  edgecolor: <>edge-color
  zorder: 6
support-props:
  arrowprops:
    shrinkA: <>support-shrink
    shrinkB: <>support-shrink
    arrowstyle: <>support-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.0

  zorder: 7
support-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>sup-color
  mec: <>edge-color
  zorder: 16

support-defend-props:
  textcoords: data
  xycoords: data
  arrowprops:
    shrinkA: <>support-defend-shrink
    shrinkB: <>support-defend-shrink
    arrowstyle: <>support-defend-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0

  zorder: 6

convoy-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>convoy-color
  mec: <>edge-color
  zorder: 16




